# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5591145a87123087f03fbd0dc22136e4"
name = "SalesInsight"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,read_inventory,write_inventory,read_locations,write_locations,write_content,read_content,write_online_store_pages"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
